# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "us1gr@nffosadyyafrooo.loacal",
  "name": "Keks",
  "password": "123456"
}
###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "us1gr@nffosadyyafrooo.loacal",
  "password": "123456"
}


###

# Check user token
POST http://localhost:3000/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDg4YTdmNzE4Zjk3NGIwYjc3MjdkNGYiLCJlbWFpbCI6InVzMWdyQG5mZm9zYWR5eWFmcm9vby5sb2FjYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTY4NjgwNzY1NCwiZXhwIjoxNjg2ODA4MjU0fQ.M_gWG8YDOPC2FDc8bOsC_bJ0-hfQeQuFj057djCSENY

###
# Create a new card
POST http://localhost:3000/api/cards HTTP/1.1
Content-Type: application/json

{
  "name": "viasdfasdfasfdeo",
  "description": "its some leettesrand little more name1",
  "picture": "https://www.youtube.com/watch?v=NYGL4hxPuxs",
  "typeOfGuitar": "электро",
  "article": "4352345",
  "numberOfStrings": 4,
  "price": 100
}
###
# Update card
PATCH  http://localhost:3000/api/cards/6489a1cf9334d88f5d4af3f3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDg4YTdmNzE4Zjk3NGIwYjc3MjdkNGYiLCJlbWFpbCI6InVzMWdyQG5mZm9zYWR5eWFmcm9vby5sb2FjYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTY4NjgwNzY1NCwiZXhwIjoxNjg2ODA4MjU0fQ.M_gWG8YDOPC2FDc8bOsC_bJ0-hfQeQuFj057djCSENY
Content-Type: application/json

{
  "name": "Heeeeeeeeeelllllo1234"
}
###
# Get post by id
GET http://localhost:3000/api/cards/6489a1cf9334d88f5d4af3f3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDg4YTdmNzE4Zjk3NGIwYjc3MjdkNGYiLCJlbWFpbCI6InVzMWdyQG5mZm9zYWR5eWFmcm9vby5sb2FjYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTY4NjgwNzY1NCwiZXhwIjoxNjg2ODA4MjU0fQ.M_gWG8YDOPC2FDc8bOsC_bJ0-hfQeQuFj057djCSENY
###

# Get cards
GET http://localhost:3000/api/cards/ HTTP/1.1
###


# Delete the post by id
DELETE http://localhost:3000/api/cards/6489d2f132812aeb53a0fbf4 HTTP/1.1

###